### ISSUE TITLE
[Yarn] Install Error: Couldn't find package "@huggingface/shared@1.0.0"

### ISSUE THREAD

**Issue by carrotfarmer** [huggingface/huggingface.js#179]
Error while trying to install `@huggingface/inference` using yarn:

<img width="954" alt="image" src="https://user-images.githubusercontent.com/66675022/235894508-ae1190f6-7b17-4088-a245-bfc2e094bbf1.png">

```
yarn add v1.22.17
[1/4] 🔍  Resolving packages...
error Couldn't find package "@huggingface/shared@1.0.0" required by "@huggingface/inference" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**OS:** macOS Monterey
**yarn version**: 1.22.17
**npm version**: 8.6.0
**node version**: 18.14.2

**Comment by carrotfarmer** [comment]
It works on npm. Dunno why it isn't working in yarn

**Comment by coyotte508** [comment]
Yarn is really opinionated, see https://yarnpkg.com/getting-started/migration#dont-use-bundledependencies :sweat_smile: 

cc @vvmnnnkv 

They recommend using `file:` instead of bundled dependencies but I'm not sure it's possible with TS types

**Comment by coyotte508** [comment]
Also  the error is because yarn tries to install the dev dependencies of `@huggingface/inference`, you should be able to fix it by telling it not to: https://stackoverflow.com/questions/49530678/why-does-yarn-install-dev-dependencies-but-i-just-need-the-builds

Btw if you're looking for a cool `yarn` replacement there's `pnpm` ;)

**Comment by carrotfarmer** [comment]
Ah alright
Thanks for the quick response!
(btw: actually switched to pnpm after this incident lmao)
