### ISSUE TITLE
add sentence embedding support to @huggingface/inference

### ISSUE THREAD

**Issue by MaazDev** [huggingface/huggingface.js#213]

**Comment by vvmnnnkv** [comment]
Hi @MaazDev 👋
You should probably use `featureExtraction` task (https://huggingface.co/tasks/feature-extraction) for this.
For example, `hf.featureExtraction({model: 'sentence-transformers/all-MiniLM-L6-v2', inputs: 'your sentence'})`
Otherwise, please provide an example of what you are trying to accomplish.

**Comment by MaazDev** [comment]
@vvmnnnkv thanks I will try this
